/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface GnosisSafeGetAddressesInterface extends utils.Interface {
  functions: {
    "addresscheck(address)": FunctionFragment;
    "bytesToString(bytes)": FunctionFragment;
    "compare(string,string)": FunctionFragment;
    "equal(string,string)": FunctionFragment;
    "getSafeAddresses(address)": FunctionFragment;
    "gnosissafeownerhere()": FunctionFragment;
    "multiwalletlist(uint256,uint256)": FunctionFragment;
    "ownersafelist(uint256)": FunctionFragment;
    "ownersafestore(uint256)": FunctionFragment;
    "payfee(address,uint256)": FunctionFragment;
    "safeaddressarray(uint256)": FunctionFragment;
    "safeaddressesinfo(uint256,address)": FunctionFragment;
    "storeGnosisSafeAddress(address,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addresscheck"
      | "bytesToString"
      | "compare"
      | "equal"
      | "getSafeAddresses"
      | "gnosissafeownerhere"
      | "multiwalletlist"
      | "ownersafelist"
      | "ownersafestore"
      | "payfee"
      | "safeaddressarray"
      | "safeaddressesinfo"
      | "storeGnosisSafeAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addresscheck",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "bytesToString",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "compare",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "equal",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSafeAddresses",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "gnosissafeownerhere",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "multiwalletlist",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "ownersafelist",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "ownersafestore",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "payfee",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "safeaddressarray",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "safeaddressesinfo",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "storeGnosisSafeAddress",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addresscheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bytesToString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "compare", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "equal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSafeAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gnosissafeownerhere",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiwalletlist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownersafelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownersafestore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payfee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeaddressarray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeaddressesinfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeGnosisSafeAddress",
    data: BytesLike
  ): Result;

  events: {
    "GnosisSafeAddress(address,string)": EventFragment;
    "getSafeAddressListEvent(string[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GnosisSafeAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "getSafeAddressListEvent"): EventFragment;
}

export interface GnosisSafeAddressEventObject {
  _walletaddressevent: string;
  _safestringevent: string;
}
export type GnosisSafeAddressEvent = TypedEvent<
  [string, string],
  GnosisSafeAddressEventObject
>;

export type GnosisSafeAddressEventFilter =
  TypedEventFilter<GnosisSafeAddressEvent>;

export interface getSafeAddressListEventEventObject {
  safeaddresskey: string[];
}
export type getSafeAddressListEventEvent = TypedEvent<
  [string[]],
  getSafeAddressListEventEventObject
>;

export type getSafeAddressListEventEventFilter =
  TypedEventFilter<getSafeAddressListEventEvent>;

export interface GnosisSafeGetAddresses extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GnosisSafeGetAddressesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addresscheck(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    bytesToString(
      byteCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { stringData: string }>;

    compare(
      _a: PromiseOrValue<string>,
      _b: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    equal(
      _a: PromiseOrValue<string>,
      _b: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getSafeAddresses(
      walletaddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    gnosissafeownerhere(overrides?: CallOverrides): Promise<[string]>;

    multiwalletlist(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    ownersafelist(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string] & { ownershere: string; safeaddressesstuff: string }
    >;

    ownersafestore(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string] & { ownershere: string; safeaddressesstuff: string }
    >;

    payfee(
      sender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    safeaddressarray(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    safeaddressesinfo(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    storeGnosisSafeAddress(
      walletaddress: PromiseOrValue<string>,
      safestring: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addresscheck(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  bytesToString(
    byteCode: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  compare(
    _a: PromiseOrValue<string>,
    _b: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  equal(
    _a: PromiseOrValue<string>,
    _b: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getSafeAddresses(
    walletaddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  gnosissafeownerhere(overrides?: CallOverrides): Promise<string>;

  multiwalletlist(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  ownersafelist(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string] & { ownershere: string; safeaddressesstuff: string }
  >;

  ownersafestore(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string] & { ownershere: string; safeaddressesstuff: string }
  >;

  payfee(
    sender: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  safeaddressarray(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  safeaddressesinfo(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  storeGnosisSafeAddress(
    walletaddress: PromiseOrValue<string>,
    safestring: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addresscheck(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    bytesToString(
      byteCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    compare(
      _a: PromiseOrValue<string>,
      _b: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    equal(
      _a: PromiseOrValue<string>,
      _b: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getSafeAddresses(
      walletaddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    gnosissafeownerhere(overrides?: CallOverrides): Promise<string>;

    multiwalletlist(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    ownersafelist(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string] & { ownershere: string; safeaddressesstuff: string }
    >;

    ownersafestore(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string] & { ownershere: string; safeaddressesstuff: string }
    >;

    payfee(
      sender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, string]>;

    safeaddressarray(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    safeaddressesinfo(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    storeGnosisSafeAddress(
      walletaddress: PromiseOrValue<string>,
      safestring: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, string] & { _walletaddress: string; _safestring: string }
    >;
  };

  filters: {
    "GnosisSafeAddress(address,string)"(
      _walletaddressevent?: PromiseOrValue<string> | null,
      _safestringevent?: PromiseOrValue<string> | null
    ): GnosisSafeAddressEventFilter;
    GnosisSafeAddress(
      _walletaddressevent?: PromiseOrValue<string> | null,
      _safestringevent?: PromiseOrValue<string> | null
    ): GnosisSafeAddressEventFilter;

    "getSafeAddressListEvent(string[])"(
      safeaddresskey?: PromiseOrValue<string>[] | null
    ): getSafeAddressListEventEventFilter;
    getSafeAddressListEvent(
      safeaddresskey?: PromiseOrValue<string>[] | null
    ): getSafeAddressListEventEventFilter;
  };

  estimateGas: {
    addresscheck(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bytesToString(
      byteCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    compare(
      _a: PromiseOrValue<string>,
      _b: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    equal(
      _a: PromiseOrValue<string>,
      _b: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getSafeAddresses(
      walletaddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    gnosissafeownerhere(overrides?: CallOverrides): Promise<BigNumber>;

    multiwalletlist(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ownersafelist(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ownersafestore(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    payfee(
      sender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    safeaddressarray(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    safeaddressesinfo(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    storeGnosisSafeAddress(
      walletaddress: PromiseOrValue<string>,
      safestring: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addresscheck(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bytesToString(
      byteCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    compare(
      _a: PromiseOrValue<string>,
      _b: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    equal(
      _a: PromiseOrValue<string>,
      _b: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getSafeAddresses(
      walletaddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    gnosissafeownerhere(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    multiwalletlist(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ownersafelist(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ownersafestore(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    payfee(
      sender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    safeaddressarray(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    safeaddressesinfo(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    storeGnosisSafeAddress(
      walletaddress: PromiseOrValue<string>,
      safestring: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
