/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface TokenSwapInterface extends utils.Interface {
  functions: {
    "buyTokensABC(uint256)": FunctionFragment;
    "buyTokensXYZ(uint256)": FunctionFragment;
    "getFees()": FunctionFragment;
    "getRatio()": FunctionFragment;
    "setFees(uint256)": FunctionFragment;
    "setRatio(uint256)": FunctionFragment;
    "swapTKA(uint256)": FunctionFragment;
    "swapTKX(uint256)": FunctionFragment;
    "tokenABC()": FunctionFragment;
    "tokenXYZ()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "buyTokensABC"
      | "buyTokensXYZ"
      | "getFees"
      | "getRatio"
      | "setFees"
      | "setRatio"
      | "swapTKA"
      | "swapTKX"
      | "tokenABC"
      | "tokenXYZ"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buyTokensABC",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "buyTokensXYZ",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "getFees", values?: undefined): string;
  encodeFunctionData(functionFragment: "getRatio", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRatio",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTKA",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTKX",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "tokenABC", values?: undefined): string;
  encodeFunctionData(functionFragment: "tokenXYZ", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "buyTokensABC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyTokensXYZ",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRatio", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRatio", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapTKA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapTKX", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenABC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenXYZ", data: BytesLike): Result;

  events: {
    "eventswapTKA(uint256,uint256,uint256)": EventFragment;
    "eventswapTKX(uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "eventswapTKA"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "eventswapTKX"): EventFragment;
}

export interface eventswapTKAEventObject {
  swapTKAcounter: BigNumber;
  initialamount: BigNumber;
  amountafter: BigNumber;
}
export type eventswapTKAEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  eventswapTKAEventObject
>;

export type eventswapTKAEventFilter = TypedEventFilter<eventswapTKAEvent>;

export interface eventswapTKXEventObject {
  swapTKXcounter: BigNumber;
  initialamount: BigNumber;
  amountafter: BigNumber;
}
export type eventswapTKXEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  eventswapTKXEventObject
>;

export type eventswapTKXEventFilter = TypedEventFilter<eventswapTKXEvent>;

export interface TokenSwap extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TokenSwapInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buyTokensABC(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buyTokensXYZ(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getFees(overrides?: CallOverrides): Promise<[BigNumber]>;

    getRatio(overrides?: CallOverrides): Promise<[BigNumber]>;

    setFees(
      _Fees: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRatio(
      _ratio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapTKA(
      amountTKA: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapTKX(
      amountTKX: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tokenABC(overrides?: CallOverrides): Promise<[string]>;

    tokenXYZ(overrides?: CallOverrides): Promise<[string]>;
  };

  buyTokensABC(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buyTokensXYZ(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getFees(overrides?: CallOverrides): Promise<BigNumber>;

  getRatio(overrides?: CallOverrides): Promise<BigNumber>;

  setFees(
    _Fees: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRatio(
    _ratio: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapTKA(
    amountTKA: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapTKX(
    amountTKX: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tokenABC(overrides?: CallOverrides): Promise<string>;

  tokenXYZ(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    buyTokensABC(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    buyTokensXYZ(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getFees(overrides?: CallOverrides): Promise<BigNumber>;

    getRatio(overrides?: CallOverrides): Promise<BigNumber>;

    setFees(
      _Fees: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRatio(
      _ratio: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    swapTKA(
      amountTKA: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapTKX(
      amountTKX: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenABC(overrides?: CallOverrides): Promise<string>;

    tokenXYZ(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "eventswapTKA(uint256,uint256,uint256)"(
      swapTKAcounter?: PromiseOrValue<BigNumberish> | null,
      initialamount?: PromiseOrValue<BigNumberish> | null,
      amountafter?: PromiseOrValue<BigNumberish> | null
    ): eventswapTKAEventFilter;
    eventswapTKA(
      swapTKAcounter?: PromiseOrValue<BigNumberish> | null,
      initialamount?: PromiseOrValue<BigNumberish> | null,
      amountafter?: PromiseOrValue<BigNumberish> | null
    ): eventswapTKAEventFilter;

    "eventswapTKX(uint256,uint256,uint256)"(
      swapTKXcounter?: PromiseOrValue<BigNumberish> | null,
      initialamount?: PromiseOrValue<BigNumberish> | null,
      amountafter?: PromiseOrValue<BigNumberish> | null
    ): eventswapTKXEventFilter;
    eventswapTKX(
      swapTKXcounter?: PromiseOrValue<BigNumberish> | null,
      initialamount?: PromiseOrValue<BigNumberish> | null,
      amountafter?: PromiseOrValue<BigNumberish> | null
    ): eventswapTKXEventFilter;
  };

  estimateGas: {
    buyTokensABC(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buyTokensXYZ(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getFees(overrides?: CallOverrides): Promise<BigNumber>;

    getRatio(overrides?: CallOverrides): Promise<BigNumber>;

    setFees(
      _Fees: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRatio(
      _ratio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapTKA(
      amountTKA: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapTKX(
      amountTKX: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tokenABC(overrides?: CallOverrides): Promise<BigNumber>;

    tokenXYZ(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    buyTokensABC(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buyTokensXYZ(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getFees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setFees(
      _Fees: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRatio(
      _ratio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapTKA(
      amountTKA: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapTKX(
      amountTKX: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tokenABC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenXYZ(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
